In [1]:
import pandas as pd
arquivo = pd.read_csv('D:/UCPEL/IA-ML/HDI-2015.csv')

In [2]:
arquivo.head()

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [3]:
y = arquivo['PhysActivity']
x = arquivo.drop('PhysActivity', axis = 1)

In [5]:
from sklearn.model_selection import train_test_split

x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3)

In [6]:
arquivo.shape

(253680, 22)

In [7]:
from sklearn.ensemble import ExtraTreesClassifier
modelo = ExtraTreesClassifier()
modelo.fit(x_treino,y_treino)

resultado = modelo.score(x_teste,y_teste)
print("Acurácia:", resultado)

Acurácia: 0.7396983075791023

In [8]:
y_teste[400:403]

161062    1.0
119263    1.0
112604    0.0
Name: PhysActivity, dtype: float64

In [9]:
x_teste[400:403]

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
161062,0.0,0.0,0.0,1.0,25.0,1.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,8.0,6.0,8.0
119263,0.0,1.0,1.0,1.0,25.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,2.0,0.0,0.0,4.0,5.0,7.0
112604,0.0,0.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,5.0,15.0,30.0,1.0,0.0,13.0,5.0,3.0

In [10]:
previsoes = modelo.predict(x_teste[400:403])

In [11]:
previsoes

array([1., 1., 0.])