In [2]:
#Carregando o conjunto de dados
import pandas as pd
arquivo = pd.read_csv('D:/UCPEL/IA-ML/HDI-2015.csv')

In [3]:
arquivo.head()

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [4]:
arquivo.tail()

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,0.0,1.0,1.0,1.0,18.0,0.0,0.0,2.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,1.0,1.0,1.0,1.0,25.0,0.0,0.0,2.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [5]:
#Separando as variÃ¡veis entre preditoras e variÃ¡vel-alvo
y = arquivo['HighBP']
x = arquivo.drop('HighBP', axis = 1)

In [6]:
from sklearn.model_selection import train_test_split

#Criando os conjuntos de dados de treino e teste:
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3)

In [7]:
arquivo.shape

(253680, 22)

In [8]:
#CriaÃ§Ã£o do modelo
from sklearn.ensemble import ExtraTreesClassifier
modelo = ExtraTreesClassifier()
modelo.fit(x_treino, y_treino)

#Imprimindo resultados
resultado = modelo.score(x_teste, y_teste)
print("AcurÃ¡cia:", resultado)

AcurÃ¡cia: 0.6985046778093136

In [9]:
y_teste[400:403]

162940    0.0
119969    1.0
179351    1.0
Name: HighBP, dtype: float64

In [10]:
x_teste[400:403]

,HeartDiseaseorAttack,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
162940,0.0,0.0,1.0,23.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,5.0,6.0
119969,0.0,1.0,1.0,25.0,1.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,10.0,5.0,7.0
179351,0.0,0.0,1.0,36.0,0.0,1.0,2.0,1.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,1.0,1.0,10.0,6.0,6.0

In [11]:
previsoes = modelo.predict(x_teste[400:403])

In [12]:
previsoes

array([0., 0., 1.])

In [ ]:
#automatizar o modelo para rodar 100x e fazer a mÃ©dia

In [5]:
#Carregando o conjunto de dados
import pandas as pd
arquivo = pd.read_csv('D:/UCPEL/IA-ML/HDI-2015.csv')

#Separando as variÃ¡veis entre preditoras e variÃ¡vel-alvo
y = arquivo['HighBP']
x = arquivo.drop('HighBP', axis = 1)

from sklearn.model_selection import train_test_split

#Criando os conjuntos de dados de treino e teste:
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3)

#CriaÃ§Ã£o do modelo
from sklearn.ensemble import ExtraTreesClassifier
modelo = ExtraTreesClassifier()
modelo.fit(x_treino, y_treino)

#Imprimindo resultados
resultado = modelo.score(x_teste, y_teste)
print("AcurÃ¡cia:", resultado)

AcurÃ¡cia: 0.6984521181541049

In [6]:
y_teste[400:403]

142766    1.0
125203    1.0
202911    0.0
Name: HighBP, dtype: float64

In [7]:
x_teste[400:403]

,HeartDiseaseorAttack,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
142766,0.0,0.0,1.0,48.0,1.0,0.0,2.0,0.0,0.0,1.0,...,1.0,0.0,4.0,0.0,30.0,1.0,0.0,10.0,4.0,8.0
125203,0.0,0.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,1.0,8.0,6.0,8.0
202911,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,0.0,2.0,0.0,1.0,7.0,6.0,8.0

In [8]:
previsoes = modelo.predict(x_teste[400:403])

In [9]:
previsoes

array([1., 0., 1.])

In [10]:
#Carregando o conjunto de dados
import pandas as pd
arquivo = pd.read_csv('D:/UCPEL/IA-ML/HDI-2015.csv')

#Separando as variÃ¡veis entre preditoras e variÃ¡vel-alvo
y = arquivo['HighBP']
x = arquivo.drop('HighBP', axis = 1)

from sklearn.model_selection import train_test_split

#Criando os conjuntos de dados de treino e teste:
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3)

#CriaÃ§Ã£o do modelo
from sklearn.ensemble import ExtraTreesClassifier
modelo = ExtraTreesClassifier()
modelo.fit(x_treino, y_treino)

#Imprimindo resultados
resultado = modelo.score(x_teste, y_teste)
print("AcurÃ¡cia:", resultado)

AcurÃ¡cia: 0.6995295910858825

In [11]:
y_teste[400:403]

119314    0.0
140079    0.0
41948     1.0
Name: HighBP, dtype: float64

In [12]:
x_teste[400:403]

,HeartDiseaseorAttack,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
119314,0.0,0.0,1.0,19.0,1.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,12.0,5.0,7.0
140079,0.0,0.0,1.0,36.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,10.0,5.0,5.0
41948,1.0,1.0,1.0,27.0,1.0,1.0,2.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,1.0,1.0,0.0,13.0,5.0,3.0

In [13]:
previsoes = modelo.predict(x_teste[400:403])

In [14]:
previsoes

array([1., 1., 1.])

In [15]:
#Carregando o conjunto de dados
import pandas as pd
arquivo = pd.read_csv('D:/UCPEL/IA-ML/HDI-2015.csv')

#Separando as variÃ¡veis entre preditoras e variÃ¡vel-alvo
y = arquivo['HighBP']
x = arquivo.drop('HighBP', axis = 1)

from sklearn.model_selection import train_test_split

#Criando os conjuntos de dados de treino e teste:
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3)

#CriaÃ§Ã£o do modelo
from sklearn.ensemble import ExtraTreesClassifier
modelo = ExtraTreesClassifier()
modelo.fit(x_treino, y_treino)

#Imprimindo resultados
resultado = modelo.score(x_teste, y_teste)
print("AcurÃ¡cia:", resultado)

AcurÃ¡cia: 0.6987411962577526

In [16]:
y_teste[400:403]

100925    0.0
196109    1.0
11139     1.0
Name: HighBP, dtype: float64

In [17]:
x_teste[400:403]

,HeartDiseaseorAttack,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
100925,0.0,0.0,1.0,20.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,1.0,5.0,0.0,0.0,0.0,10.0,6.0,8.0
196109,0.0,0.0,1.0,32.0,1.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,7.0,5.0,8.0
11139,0.0,0.0,1.0,37.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,4.0,0.0,7.0,0.0,0.0,9.0,4.0,3.0

In [19]:
previsoes = modelo.predict(x_teste[400:403])

In [20]:
previsoes

array([0., 0., 1.])

In [21]:
#Carregando o conjunto de dados
import pandas as pd
arquivo = pd.read_csv('D:/UCPEL/IA-ML/HDI-2015.csv')

#Separando as variÃ¡veis entre preditoras e variÃ¡vel-alvo
y = arquivo['HighBP']
x = arquivo.drop('HighBP', axis = 1)

from sklearn.model_selection import train_test_split

#Criando os conjuntos de dados de treino e teste:
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3)

#CriaÃ§Ã£o do modelo
from sklearn.ensemble import ExtraTreesClassifier
modelo = ExtraTreesClassifier()
modelo.fit(x_treino, y_treino)

#Imprimindo resultados
resultado = modelo.score(x_teste, y_teste)
print("AcurÃ¡cia:", resultado)

AcurÃ¡cia: 0.6987280563439504

In [22]:
y_teste[400:403]

129313    1.0
140978    1.0
204032    0.0
Name: HighBP, dtype: float64

In [23]:
x_teste[400:403]

,HeartDiseaseorAttack,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
129313,0.0,1.0,1.0,32.0,1.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,4.0,1.0,5.0,1.0,1.0,12.0,6.0,7.0
140978,0.0,0.0,1.0,35.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,9.0,6.0,7.0
204032,1.0,1.0,1.0,25.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,1.0,9.0,6.0,8.0

In [24]:
previsoes = modelo.predict(x_teste[400:403])

In [25]:
previsoes

array([1., 1., 0.])

In [26]:
#Carregando o conjunto de dados
import pandas as pd
arquivo = pd.read_csv('D:/UCPEL/IA-ML/HDI-2015.csv')

#Separando as variÃ¡veis entre preditoras e variÃ¡vel-alvo
y = arquivo['HighBP']
x = arquivo.drop('HighBP', axis = 1)

from sklearn.model_selection import train_test_split

#Criando os conjuntos de dados de treino e teste:
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3)

#CriaÃ§Ã£o do modelo
from sklearn.ensemble import ExtraTreesClassifier
modelo = ExtraTreesClassifier()
modelo.fit(x_treino, y_treino)

#Imprimindo resultados
resultado = modelo.score(x_teste, y_teste)
print("AcurÃ¡cia:", resultado)

AcurÃ¡cia: 0.6961000735835173

In [27]:
y_teste[400:403]

57020     1.0
197504    1.0
85196     1.0
Name: HighBP, dtype: float64

In [28]:
x_teste[400:403]

,HeartDiseaseorAttack,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
57020,1.0,1.0,1.0,30.0,1.0,1.0,2.0,0.0,1.0,1.0,...,1.0,0.0,5.0,5.0,5.0,1.0,1.0,10.0,4.0,1.0
197504,0.0,0.0,1.0,23.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,10.0,4.0,8.0
85196,0.0,1.0,1.0,25.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,4.0,8.0

In [29]:
previsoes = modelo.predict(x_teste[400:403])

In [30]:
previsoes

array([1., 0., 0.])